DROP DATABASE IF EXISTS iFitNut_db;
CREATE DATABASE iFitNut_db;

USE iFitNut_db;

CREATE TABLE Users(
  UserID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(30) NOT NULL,
  LastName VARCHAR(30) NOT NULL,
  DOB DATE NOT NULL,
  UserName VARCHAR(30) NOT NULL,
  UserEmail VARCHAR(30) NOT NULL
);

CREATE TABLE UserFitID(
  UserID INTEGER NOT NULL AUTO_INCREMENT,
  RecordingDate DATE NOT NULL,
  Ht INT(30) NOT NULL,
  Wt INT(30) NOT NULL,
  PushUps INT(30) NOT NULL,
  SitUps INT(30) NOT NULL,
  PullUps INT(30) NOT NULL,
  RunTime INT(30) NOT NULL,
  FOREIGN KEY (UserID)
  REFERENCES Users(UserID)
);
